module.exports = [
  "art/sprites/guyjumpleft.png"
  ,"art/sprites/guyjumpright.png"
  ,"art/sprites/guywalkleft.png"
  ,"art/sprites/guywalkright.png"
  ,"art/sprites/guyleft.png"
  ,"art/sprites/guyright.png"
  ,"art/sprites/sweatleft.png"
  
  ,"art/sprites/earth.png"
  ,"art/sprites/earthGRASS.png"
  ,"art/sprites/clouds.png"
  ,"art/sprites/background64.png"

  ,"art/sprites/apple.png"
  ,"art/sprites/brocoli.png"
  ,"art/sprites/candy.png"
  ,"art/sprites/carrot.png"
  ,"art/sprites/cupobstacle.png"
  ,"art/sprites/icecream.png"
  ,"art/sprites/orange.png"
  ,"art/sprites/strawberry.png"
  ,"art/sprites/water.png"
  ,"art/sprites/watermelon.png"
  
  ,"art/sprites/hydrationbar.png"
  ,"art/sprites/healthbar.png"
  ,"art/sprites/flag.png"
  ,"art/sprites/chocolate.png"
  ,"art/sprites/banana.png"
  ,"art/sprites/YouWin.png"
  ,"art/sprites/sweatleft.png"
  ,"art/sprites/sweatright.png"
  ,"art/sprites/VITAMAN.png"
]